###TEST CREATE STOCK
POST http://localhost:8080/stocks
Content-Type: application/json

{
  "companyId": 3,
  "initialPrice": 50.0
}

###TEST GET STOCK
GET http://localhost:8080/stocks/1

###TEST GET ALL STOCKS
GET http://localhost:8080/stocks

### TEST STOCK PRICE STREAM
GET http://localhost:8080/stocks/stream

### TEST STOCK PRICE HISTORY
GET http://localhost:8080/stocks/1/history