
###TEST LOGIN
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "condeco@kotlin.com",
  "password": "kotlinzaoze"
}


###TEST USER INFO
GET http://localhost:8080/me
Authorization: bearer hWIzJHfValaEKBZBx78fvjX5IlGWzohSCSVndrL7l_U
Content-Type: application/json


###TEST LOGOUT
POST http://localhost:8080/users/logout
Authorization: bearer SKOrpY8RiTwLNiPu-Gk7YNb6leIt7S-SkrInVP3Wgb8
Content-Type: application/json


###TEST CREATE USER

POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "kingOfTheLimbs",
  "email": "kingy@kotlin.com",
  "password": "limBzz23gfff"
}