
###TEST LOGIN
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "fredws2005@hotmail.com",
  "password": "qwertY_12"
}


###TEST USER INFO
GET http://localhost:8080/me
Authorization: bearer 7ILcyORC04AlYp3_bK_cZFFzhb8f9tsjO4xhWmiXQl8
Content-Type: application/json


###TEST LOGOUT

POST http://localhost:8080/users/logout
Authorization: bearer 7ILcyORC04AlYp3_bK_cZFFzhb8f9tsjO4xhWmiXQl8
Content-Type: application/json


###TEST CREATE USER

POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "freddie",
  "email": "fredws2005@hotmail.com",
  "password": "qwertY_12"
}